sudo: required
dist: trusty
language: node_js
node_js: 7.3
addons:
  firefox: "52.3.0"
services:
  - mongodb
cache: yarn
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - donejs develop &
script:
  - sudo sh -c "dbus-uuidgen > /etc/machine-id"
  - npm run test
  - npm run test-cypress
after_script:
  - kill $(jobs -p) || true