sudo: required
dist: trusty
language: node_js
node_js: 8.6.0
addons:
  firefox: "latest"
services: mongodb
cache:
  yarn: true
  directories:
    - api
    - ~/.cache
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Clone backend repo
  - "[ -d api/.git ] || git clone git@github.com:Equibit/wallet-api.git api"
  - "cd api"
  - "git reset --hard"
  - "git clean -f"
  - "git pull"
  # Install dependencies
  - "yarn install"
  # Run server
  - "yarn run e2e &"
  # Wait for server to start
  - "sleep 5"
  - "cd .."
install:
  - yarn install --frozen-lockfile
script:
  - sudo sh -c "dbus-uuidgen > /etc/machine-id"
  - yarn run $TEST_SUITE
after_script:
  - kill $(jobs -p) || true
  - sudo service mongodb stop
jobs:
  include:
    - stage: Testing
      env:
        - TEST_SUITE=cypress-test
      <<: *defaults
    - stage: Testing
      env:
        - TEST_SUITE=test
      <<: *defaults