sudo: required
language: node_js
node_js: 7.3
addons:
  firefox: "51.0"
cache: yarn
before_install:
  - "export DISPLAY=:99.0"
  - "export DEBUG=testee:*"
  - "sh -e /etc/init.d/xvfb start"
script:
  - sudo sh -c "dbus-uuidgen > /etc/machine-id"
