sudo: required
dist: trusty
language: node_js
node_js: 8.6.0
cache:
  yarn: true
  directories:
    - api
    - ~/.cache
defaults: &defaults
  addons:
    firefox: "latest"
    chrome: "stable"
  services: mongodb
  install:
    - yarn
  script:
    - sudo sh -c "dbus-uuidgen > /etc/machine-id"
    - yarn run $TEST_SUITE
  after_script:
    - kill $(jobs -p) || true
    - sudo service mongodb stop
before: &before
  before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    # Clone backend repo
    - "[ -d api/.git ] || git clone git@github.com:Equibit/wallet-api.git api"
    - "cd api"
    # Reset the repo so we can have a conflict-less pull
    - "git reset --hard"
    - "git clean -f"
    - "git pull"
    # Install dependencies
    - "yarn install"
    # Run server
    - "yarn run e2e &"
    # Wait for server to start
    - "sleep 5"
    - "cd .."
jobs:
  include:
  # Parallel testing suites - 1 for transactions, 2 for all other e2e, 1 for unit tests
    - stage: Testing
      env:
        - TEST_SUITE=cypress-transactions
      <<: *before
      <<: *defaults
    - stage: Testing
      env:
        - TEST_SUITE=cypress-test
      <<: *before
      <<: *defaults
    - stage: Testing
      env:
        - TEST_SUITE=test
      <<: *defaults
