sudo: required
dist: trusty
language: node_js
node_js: 7.3
addons:
  firefox: "52.3.0"
cache:
  yarn: true
  directories:
    - api
services:
  - mongodb
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Fire up database
  - "mongod --fork --syslog &"
  # Clone backend repo
  - "[ -d api/.git ] || git clone git@github.com/Equibit/wallet-api.git api"
  - "cd api"
  # Reset the repo so we can have a conflict-less pull
  - "git reset --hard"
  - "git clean -f"
  - "git pull"
  # Install dependencies
  - "npm install"
  # Run server
  - "npm start &"
  # Wait for server to start
  - "sleep 5"
  - "cd .."
script:
  - sudo sh -c "dbus-uuidgen > /etc/machine-id"
  - npm run test
  - npm run test-cypress
after_script:
  - kill $(jobs -p) || true
  - mongod --shutdown
  - pkill node