sudo: required
dist: trusty
language: node_js
node_js: 8.6.0
addons:
  firefox: "52.3.0"
cache:
  yarn: true
  directories:
    - api
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
    # Fire up database
  - "sudo mkdir -p /data/db"
  - "sudo chown -R `id -u` /data/db"
  - "sudo chmod -R go+w /data/db"
  - "mongod &"
  - "sleep 5"
  # Clone backend repo
  - "[ -d api/.git ] || git clone git@github.com:Equibit/wallet-api.git api"
  - "cd api"
  # Run server
  - "TESTING=true NODE_ENV=testing npm start &"
  # Wait for server to start
  - "sleep 10"
  - "cd .."
script:
  - sudo sh -c "dbus-uuidgen > /etc/machine-id"
  - npm run test
  - npm run test-cypress
after_script:
  - kill $(jobs -p) || true
  - mongod --shutdown
  - pkill node