language: node_js
node_js: 7.3
cache: yarn
addons:
  firefox: "latest-esr"
  # Install D-Bus here
  apt:
    packages:
      - dbus-x11
before_install:
  - "export DISPLAY=:99.0"
  - "export DEBUG=testee:*"
  - "sh -e /etc/init.d/xvfb start"
